package com.weidays.parentsbank.server.entity.po;

// Generated 2013-12-16 16:00:06 by Hibernate Tools 3.4.0.CR1


/**
 * UserInfo generated by hbm2java
 */
public class BankOwner implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String nickname;
	private String realName;
	private String password;
	private String gender;
	private String birthday;
	private String email;
	private String phoneNumber;
	private String avatar;
	private String rigistTime;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getNickname() {
		return nickname;
	}
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}
	public String getRealName() {
		return realName;
	}
	public void setRealName(String realName) {
		this.realName = realName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	public String getBirthday() {
		return birthday;
	}
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public String getAvatar() {
		return avatar;
	}
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}
	public String getRigistTime() {
		return rigistTime;
	}
	public void setRigistTime(String rigistTime) {
		this.rigistTime = rigistTime;
	}

	

}
