package com.weidays.parentsbank.server.entity.po;

// Generated 2013-12-24 16:43:01 by Hibernate Tools 3.4.0.CR1


/**
 * FavourLog generated by hbm2java
 */
public class FavourLog implements java.io.Serializable {

	private Integer logId;
	private int busiId;
	private int hilifeId;
	private String favourTime;
	private String busiType;

	public FavourLog() {
	}

	public FavourLog(int busiId, int hilifeId, String favourTime) {
		this.busiId = busiId;
		this.hilifeId = hilifeId;
		this.favourTime = favourTime;
	}

	public FavourLog(int busiId, int hilifeId, String favourTime, String busiType) {
		this.busiId = busiId;
		this.hilifeId = hilifeId;
		this.favourTime = favourTime;
		this.busiType = busiType;
	}

	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public int getBusiId() {
		return this.busiId;
	}

	public void setBusiId(int busiId) {
		this.busiId = busiId;
	}

	public int getHilifeId() {
		return this.hilifeId;
	}

	public void setHilifeId(int hilifeId) {
		this.hilifeId = hilifeId;
	}

	public String getFavourTime() {
		return this.favourTime;
	}

	public void setFavourTime(String favourTime) {
		this.favourTime = favourTime;
	}

	public String getBusiType() {
		return this.busiType;
	}

	public void setBusiType(String busiType) {
		this.busiType = busiType;
	}

}
