package com.weidays.parentsbank.server.entity.po;

// Generated 2013-12-16 16:00:06 by Hibernate Tools 3.4.0.CR1


/**
 * PicInfo generated by hbm2java
 */
public class PicInfo implements java.io.Serializable {

	private Integer picId;
	private int hilifeId;
	private String picName;
	private String picUrl;
	private String uploadTime;

	public PicInfo() {
	}

	public PicInfo(int hilifeId, String picName, String picUrl, String uploadTime) {
		this.hilifeId = hilifeId;
		this.picName = picName;
		this.picUrl = picUrl;
		this.uploadTime = uploadTime;
	}

	public Integer getPicId() {
		return this.picId;
	}

	public void setPicId(Integer picId) {
		this.picId = picId;
	}

	public int getHilifeId() {
		return this.hilifeId;
	}

	public void setHilifeId(int hilifeId) {
		this.hilifeId = hilifeId;
	}

	public String getPicName() {
		return this.picName;
	}

	public void setPicName(String picName) {
		this.picName = picName;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public String getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(String uploadTime) {
		this.uploadTime = uploadTime;
	}

}
