package com.weidays.parentsbank.server.entity.po;

// Generated 2013-12-16 16:00:06 by Hibernate Tools 3.4.0.CR1


/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer hilifeId;
	private String userName;
	private String nickname;
	private String realName;
	private String password;
	private String gender;
	private String birthday;
	private String constellation;
	private String bloodType;
	private String email;
	private String phoneNumber;
	private String avatar;
	private String saying;
	private String areaCode;
	private String rigistTime;
	private String bgImage;

	public UserInfo() {
	}

	public UserInfo(String userName, String password, String areaCode,
			String rigistTime) {
		this.userName = userName;
		this.password = password;
		this.areaCode = areaCode;
		this.rigistTime = rigistTime;
	}

	public UserInfo(String userName, String nickname, String realName,
			String password, String gender, String birthday,
			String constellation, String bloodType, String email,
			String phoneNumber, String avatar, String saying, String areaCode,
			String rigistTime, String bgImage) {
		this.userName = userName;
		this.nickname = nickname;
		this.realName = realName;
		this.password = password;
		this.gender = gender;
		this.birthday = birthday;
		this.constellation = constellation;
		this.bloodType = bloodType;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.avatar = avatar;
		this.saying = saying;
		this.areaCode = areaCode;
		this.rigistTime = rigistTime;
		this.bgImage = bgImage;
	}

	public Integer getHilifeId() {
		return this.hilifeId;
	}

	public void setHilifeId(Integer hilifeId) {
		this.hilifeId = hilifeId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	

	public String getConstellation() {
		return this.constellation;
	}

	public void setConstellation(String constellation) {
		this.constellation = constellation;
	}

	public String getBloodType() {
		return this.bloodType;
	}

	public void setBloodType(String bloodType) {
		this.bloodType = bloodType;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getSaying() {
		return this.saying;
	}

	public void setSaying(String saying) {
		this.saying = saying;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getRigistTime() {
		return this.rigistTime;
	}

	public void setRigistTime(String rigistTime) {
		this.rigistTime = rigistTime;
	}

	public String getBgImage() {
		return this.bgImage;
	}

	public void setBgImage(String bgImage) {
		this.bgImage = bgImage;
	}

}
