package com.weidays.parentsbank.server.entity.po;

// Generated 2013-12-16 16:00:06 by Hibernate Tools 3.4.0.CR1

/**
 * UserDynamic generated by hbm2java
 */
public class UserDynamic implements java.io.Serializable {

	private Integer dynamicId;
	private int hilifeId;
	private String sendTime;
	private String sendContent;
	private String dynamicType;

	public UserDynamic() {
	}

	public UserDynamic(int hilifeId, String sendTime, String sendContent,
			String dynamicType) {
		this.hilifeId = hilifeId;
		this.sendTime = sendTime;
		this.sendContent = sendContent;
		this.dynamicType = dynamicType;
	}

	public Integer getDynamicId() {
		return this.dynamicId;
	}

	public void setDynamicId(Integer dynamicId) {
		this.dynamicId = dynamicId;
	}

	public int getHilifeId() {
		return this.hilifeId;
	}

	public void setHilifeId(int hilifeId) {
		this.hilifeId = hilifeId;
	}

	public String getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(String sendTime) {
		this.sendTime = sendTime;
	}

	public String getSendContent() {
		return this.sendContent;
	}

	public void setSendContent(String sendContent) {
		this.sendContent = sendContent;
	}

	public String getDynamicType() {
		return this.dynamicType;
	}

	public void setDynamicType(String dynamicType) {
		this.dynamicType = dynamicType;
	}

}
