package com.weidays.parentsbank.server.entity.bo;

// Generated 2013-12-16 16:00:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import com.weidays.parentsbank.server.entity.po.PictureShare;

/**
 * PictureShare generated by hbm2java
 */
public class PictureShareBo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4798155520702206192L;
	private Integer shareId;
	private int hilifeId;
	private String title;
	private String content;
	private String sendTime;
	private String sendCity;
	private String sentLocation;
	private double longitude;
	private double latitude;
	private String source;
	private int fromShareId;
	private List<Integer> picIds;
	private List<String> picUrls;
	//private String picIds;
	
	

	public Integer getShareId() {
		return this.shareId;
	}

	public void setPicIds(List<Integer> picIds) {
		this.picIds = picIds;
	}

	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	public int getHilifeId() {
		return this.hilifeId;
	}

	public void setHilifeId(int hilifeId) {
		this.hilifeId = hilifeId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(String sendTime) {
		this.sendTime = sendTime;
	}

	public String getSendCity() {
		return this.sendCity;
	}

	public void setSendCity(String sendCity) {
		this.sendCity = sendCity;
	}

	public String getSentLocation() {
		return this.sentLocation;
	}

	public void setSentLocation(String sentLocation) {
		this.sentLocation = sentLocation;
	}

	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}



	public List<Integer> getPicIds() {
		return picIds;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public int getFromShareId() {
		return fromShareId;
	}

	public void setFromShareId(int fromShareId) {
		this.fromShareId = fromShareId;
	}

	
	public List<String> getPicUrls() {
		return picUrls;
	}

	public void setPicUrls(List<String> picUrls) {
		this.picUrls = picUrls;
	}

	public void create(PictureShare x, List<Integer> picIds2,List<String> picUrls2) {
		this.content=x.getContent();
		this.hilifeId=x.getHilifeId();
		this.latitude=x.getLatitude();
		this.longitude=x.getLongitude();
		this.picIds=picIds2;
		this.picUrls=picUrls2;
		this.sendCity=x.getSendCity();
		this.sendTime=x.getSendTime();
		this.sentLocation=x.getSentLocation();
		this.shareId=x.getShareId();
		this.title=x.getTitle();
		this.source=x.getSource();
		this.fromShareId=x.getFromShareId();
	}
	

}
